name: wokriot_app
description: Ung dung cham cong da diem WOKRIOT-4735
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- GIAO DIỆN CƠ BẢN ---
  cupertino_icons: ^1.0.6

  # --- LOGIC WOKRIOT ---
  
  # 1. Để gọi API (Login, gửi đơn từ lên Backend)
  http: ^1.2.0
  
  # 2. Để lưu Token đăng nhập, thông tin user cục bộ
  shared_preferences: ^2.2.0
  
  # 3. Format ngày giờ (Ví dụ: 24/12/2025)
  intl: ^0.19.0
  
  # 4. Quản lý trạng thái (State Management)
  provider: ^6.1.5+1
  
  # 5. Hiển thị thông báo (Quan trọng cho logic check-in thụ động)
  flutter_local_notifications: ^17.0.0
  
  # 6. Điều hướng trang (Login -> Home)
  go_router: ^14.0.0
  
  # 7. Tạo mã QR (Dùng cho tính năng Thẻ nhân viên ảo/Virtual ID)
  qr_flutter: ^4.1.0

  # 8. [QUAN TRỌNG] Giao thức MQTT 
  # Giúp App lắng nghe tín hiệu "bíp" từ ESP32/Server gửi về
  mqtt_client: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/